### ISSUE TITLE
I can pass Dumper to yaml.dumps but not Loader to yaml.loads

### ISSUE THREAD

**Issue by palewire** [eyeseast/python-frontmatter#24]
Seems like a bug. I'd love to patch. What can I do?

**Comment by eyeseast** [comment]
Sort of a bug, maybe a design flaw. Possibly depends on what a different Loader does.

I *[just](https://github.com/eyeseast/python-frontmatter/pull/15)* merged in a feature that lets you load other kinds of frontmatter -- JSON, TOML, other things -- but for now you can only dump out YAML. So that complicates the loading process a little and makes loading and dumping less symmetrical.

Handlers are defined [here](https://github.com/eyeseast/python-frontmatter/blob/master/frontmatter/default_handlers.py). I haven't had a chance to document custom loaders yet, but I will.

I think what needs to happen is that a handler needs to take additional `**kwargs` in its `load` method. That gets called [here](https://github.com/eyeseast/python-frontmatter/blob/master/frontmatter/__init__.py#L72). You could pass in `**defaults` from above, pop out `Loader` or whatever, and customize loading that way.

**Comment by eyeseast** [comment]
Thinking about this a bit more, we could use handlers on both ends, for loading and dumping. The tricky part is that a loading handler is chosen based on the separator (`---` or `+++` or `{`). 

When I load a post, I could store the hander used on the `Post` object, and then use that again when dumping, unless I override it. So an API might look like this:

```python
post = frontmatter.load('example.md', handler=YAMLHandler(), title='Awesome YAML')
json_text = frontmatter.dumps(post, handler=JSONHandler())
yaml_text = frontmatter.dumps(post) # still uses YAMLHandler from above

post.handler = TOMLHandler() # now it defaults to TOML when dumping
```

Would that be useful? You could write a handler to do anything you need, overriding methods for parsing and exporting (maybe also default delimiters).

**Comment by palewire** [comment]
Hmm. I dunno. The thing I was attempting was to substitute the [ruamel.yaml](https://pypi.python.org/pypi/ruamel.yaml) loader and dumper so that I could preserve comments and substitute an ordered dictionary.

**Comment by eyeseast** [comment]
So, the thing I want to avoid here is adding lots of special case arguments, especially now that multiple formats are supported. We could add in the ability to pass in `**kwargs` in `YAMLHandler.load` or `BaseHandler.load`, but there's a limit to how much customization should happen in that function. At a certain point, it's easier to say, subclass `YAMLHandler` and run your own method to load frontmatter.

**Comment by drakeguan** [comment]
Hi, I just did a simple, not that elegant but just a proof of concept, commit to allow custom dumper while calling `dump()` or `dumps()`. Here is the initial idea as a branch, https://github.com/drakeguan/python-frontmatter/tree/custom_dumper. If anyone are interested, please leave your comments. And hopefully, the author, @eyeseast, can provide further feedback to make it as complete as possible to merge back eventually.

**Comment by eyeseast** [comment]
This is now possible, and easier, using custom handlers. I think it can still be made a little easier (and a little better documented). Here's how you'd do it now:

```python
import frontmatter
from frontmatter.default_handlers import YAMLHandler

class CustomYAMLHandler(YAMLHandler):
    def load(self, fm, **kwargs):
        return yaml.load(fm, Loader=CustomLoaderClass)

frontmatter.load('file.md', handler=CustomYAMLHandler())
```
